model:
  module: models.motion_predictor.TMDM_aligner.Aligner
  params:
    diffuser_config:
      module: models.motion_predictor.TMDM.ToothDiffuser
      params:
        num_teeth: 32
        num_step: 20
        njoints: 4
        nfeats: 3
        shape_dim: 512
        hidden_size: 256
        num_layers: 3
        noise_steps: 100
        beta_1: 1e-4
        beta_T: 0.05

    optimizer_config:
      module: torch.optim.AdamW
      weight_decay: 0.05
      betas: [0.9, 0.95]
      eps: 1e-8

    scheduler_config:
      module: pl_bolts.optimizers.lr_scheduler.LinearWarmupCosineAnnealingLR
      params:
        warmup_epochs: 5
        warmup_start_lr: 0.0
        eta_min: 1e-7

dataset:
  module: dataset.style_transfer.MotionDataManager
  params:
    data_path: /data3/wyx/GenDental/data/motion_literature_aug_1to1/motion_oneformer3d_aug_1to1
    index_path: /data3/wyx/GenDental/files/motion_oneformer3d_aug_1to1
    batch_size: 16
